name: Deploy clinica-medica

on:
   push:
    branches: [main]

jobs: 
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Deploy to Server
              uses: easingthemes/ssh-deploy@main
              with:
                  SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_KEY }}
                  ARGS: "-rlgoDzvc -i --delete"
                  SOURCE: "docker-compose.yaml"
                  REMOTE_HOST: ${{ secrets.AWS_REMOTE_HOST }}
                  REMOTE_USER: ${{ secrets.AWS_REMOTE_USER }}
                  TARGET: ${{ secrets.AWS_TARGET_DIR }}