name: Deploy clinica-medica

on:
   push:
    branches: [main]

jobs: 
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@v1.2.0
              with:
                host: ${{ secrets.AWS_REMOTE_HOST }}
                username: ubuntu
                passphrase: ${{ secrets.AWS_SSH_KEY }}
                password: guntz-aws
                script: ls