name: Deploy clinica-medica

on:
   push:
    branches: [main]

jobs: 
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

#            - name: Fazendo configuracao do java
#              uses: actions/setup-java@v3
#              with:
#                java-version: '17'
#                distribution: 'temurin'